"""add generated_images table

Revision ID: 536af074756e
Revises: 92cad9f06612
Create Date: 2026-01-22 14:11:44.545927

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '536af074756e'
down_revision: Union[str, Sequence[str], None] = '92cad9f06612'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('generated_images',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=True),
    sa.Column('canvas_project_id', sa.UUID(), nullable=True),
    sa.Column('image_url', sa.String(length=500), nullable=False),
    sa.Column('thumbnail_url', sa.String(length=500), nullable=True),
    sa.Column('prompt', sa.Text(), nullable=False),
    sa.Column('generation_params', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('image_type', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('is_selected', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_generated_images_canvas_project_id'), 'generated_images', ['canvas_project_id'], unique=False)
    op.create_index(op.f('ix_generated_images_created_at'), 'generated_images', ['created_at'], unique=False)
    op.create_index(op.f('ix_generated_images_session_id'), 'generated_images', ['session_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_generated_images_session_id'), table_name='generated_images')
    op.drop_index(op.f('ix_generated_images_created_at'), table_name='generated_images')
    op.drop_index(op.f('ix_generated_images_canvas_project_id'), table_name='generated_images')
    op.drop_table('generated_images')
    # ### end Alembic commands ###
