"""add design_briefs table

Revision ID: 57b440e30abe
Revises: dbaa1c302ed6
Create Date: 2026-01-25 22:22:04.463586

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '57b440e30abe'
down_revision: Union[str, Sequence[str], None] = 'dbaa1c302ed6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('design_briefs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('chat_session_id', sa.UUID(), nullable=True),
    sa.Column('canvas_project_id', sa.UUID(), nullable=True),
    sa.Column('concept_info', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('shoe_spec', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('marketing_context', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['canvas_project_id'], ['canvas_projects.id'], ),
    sa.ForeignKeyConstraint(['chat_session_id'], ['chat_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_design_briefs_canvas_project_id'), 'design_briefs', ['canvas_project_id'], unique=True)
    op.create_index(op.f('ix_design_briefs_chat_session_id'), 'design_briefs', ['chat_session_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_design_briefs_chat_session_id'), table_name='design_briefs')
    op.drop_index(op.f('ix_design_briefs_canvas_project_id'), table_name='design_briefs')
    op.drop_table('design_briefs')
    # ### end Alembic commands ###
