"""Add canvas and design package models

Revision ID: 7458c80a0ab7
Revises: de84b91407f7
Create Date: 2026-01-24 15:28:55.612150

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7458c80a0ab7'
down_revision: Union[str, Sequence[str], None] = 'de84b91407f7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('canvas_layers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('canvas_project_id', sa.UUID(), nullable=False),
    sa.Column('layer_type', sa.String(length=50), nullable=False),
    sa.Column('layer_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('z_index', sa.Integer(), nullable=False),
    sa.Column('is_visible', sa.Boolean(), nullable=False),
    sa.Column('is_locked', sa.Boolean(), nullable=False),
    sa.Column('opacity', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_canvas_layers_canvas_project_id'), 'canvas_layers', ['canvas_project_id'], unique=False)
    op.create_table('canvas_projects',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('canvas_state', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_canvas_projects_project_id'), 'canvas_projects', ['project_id'], unique=False)
    op.create_index(op.f('ix_canvas_projects_user_id'), 'canvas_projects', ['user_id'], unique=False)
    op.create_table('design_images',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('design_package_id', sa.UUID(), nullable=False),
    sa.Column('image_type', sa.String(length=50), nullable=False),
    sa.Column('image_url', sa.String(length=500), nullable=False),
    sa.Column('thumbnail_url', sa.String(length=500), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_design_images_design_package_id'), 'design_images', ['design_package_id'], unique=False)
    op.create_table('design_packages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=True),
    sa.Column('chat_session_id', sa.UUID(), nullable=True),
    sa.Column('canvas_project_id', sa.UUID(), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('package_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('color_palette', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_design_packages_created_at'), 'design_packages', ['created_at'], unique=False)
    op.create_index(op.f('ix_design_packages_project_id'), 'design_packages', ['project_id'], unique=False)
    op.create_index(op.f('ix_design_packages_user_id'), 'design_packages', ['user_id'], unique=False)
    op.create_table('examples',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_examples_id'), 'examples', ['id'], unique=False)
    op.create_table('market_reports',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('design_package_id', sa.UUID(), nullable=False),
    sa.Column('market_analysis', sa.Text(), nullable=True),
    sa.Column('cost_analysis', sa.Text(), nullable=True),
    sa.Column('trend_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('competitor_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('chart_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_market_reports_design_package_id'), 'market_reports', ['design_package_id'], unique=False)
    op.create_table('production_assets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('design_package_id', sa.UUID(), nullable=False),
    sa.Column('asset_type', sa.String(length=50), nullable=False),
    sa.Column('asset_url', sa.String(length=500), nullable=True),
    sa.Column('thumbnail_url', sa.String(length=500), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('generation_params', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_production_assets_design_package_id'), 'production_assets', ['design_package_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_production_assets_design_package_id'), table_name='production_assets')
    op.drop_table('production_assets')
    op.drop_index(op.f('ix_market_reports_design_package_id'), table_name='market_reports')
    op.drop_table('market_reports')
    op.drop_index(op.f('ix_examples_id'), table_name='examples')
    op.drop_table('examples')
    op.drop_index(op.f('ix_design_packages_user_id'), table_name='design_packages')
    op.drop_index(op.f('ix_design_packages_project_id'), table_name='design_packages')
    op.drop_index(op.f('ix_design_packages_created_at'), table_name='design_packages')
    op.drop_table('design_packages')
    op.drop_index(op.f('ix_design_images_design_package_id'), table_name='design_images')
    op.drop_table('design_images')
    op.drop_index(op.f('ix_canvas_projects_user_id'), table_name='canvas_projects')
    op.drop_index(op.f('ix_canvas_projects_project_id'), table_name='canvas_projects')
    op.drop_table('canvas_projects')
    op.drop_index(op.f('ix_canvas_layers_canvas_project_id'), table_name='canvas_layers')
    op.drop_table('canvas_layers')
    # ### end Alembic commands ###
