"""Add composite index for recent designs

Revision ID: dbaa1c302ed6
Revises: 7458c80a0ab7
Create Date: 2026-01-25 13:40:41.637823

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dbaa1c302ed6'
down_revision: Union[str, Sequence[str], None] = '7458c80a0ab7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_canvas_projects_user_updated', 'canvas_projects', ['user_id', sa.literal_column('updated_at DESC')], unique=False)
    op.create_index('idx_chat_sessions_user_updated', 'chat_sessions', ['user_id', sa.literal_column('updated_at DESC')], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_chat_sessions_user_updated', table_name='chat_sessions')
    op.drop_index('idx_canvas_projects_user_updated', table_name='canvas_projects')
    # ### end Alembic commands ###
